"""
Django settings for admin_crm project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@-rhjr%kda1t!31s55&r!n*i0rg8h&*7ld9_nt-vte*z_m1^7x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False
ALLOWED_HOSTS = ['65.0.45.255', 'solar365.co.in', '172.31.7.248', '65.1.123.138', '127.0.0.1', 'localhost']
# ALLOWED_HOSTS = ['*']



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'common',
    'module',
    'other_component',
    'inverters',
    'batteries',
    'invoice',
    'account',
    'grid_approval',
    'installation',
    'order',
    'call_support',
    
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]


CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = 'admin_crm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WKHTMLTOPDF_PATH = '/home/admin1/.local/lib/python3.10/site-packages/wkhtmltopdf'  # Set the path to the wkhtmltopdf executable

# DEFAULT_AUTHENTICATION_CLASSES: [
#     # 'rest_framework.authentication.SessionAuthentication',
#     'rest_framework.authentication.BasicAuthentication',
# ]
AUTH_USER_MODEL = "common.User"


WSGI_APPLICATION = 'admin_crm.wsgi.application'

# AUTHENTICATION_BACKENDS = (
#     # 'django.contrib.auth.backends.ModelBackend',
#     'common.backend.EmailBackend',
# )
# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#        'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'admin_panel',
#         'USER': 'root',
#         'PASSWORD': 'Pass@wo1',
#         'HOST': 'localhost',   # Or an IP Address that your DB is hosted on 
#         'PORT': '3306',
#     }
# }   

# DATABASES = {
#     'default': {
#        'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'SOLAR_DATABASE',
#         'USER': 'admin',
#         'PASSWORD': '10101990',
#         'HOST': 'database-1.cjw6dhv0hucp.ap-south-1.rds.amazonaws.com',   # Or an IP Address that your DB is hosted on 
#         'PORT': '3306',
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#        'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'SOLAR_DATABASE',
#         'USER': 'admin',
#         'PASSWORD': '10101990',
#         'HOST': 'database-1.cjw6dhv0hucp.ap-south-1.rds.amazonaws.com',   # Or an IP Address that your DB is hosted on 
#         'PORT': '3306',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
REST_FRAMEWORK = {
    # 'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',

    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        # 'rest_framework.authentication.SessionAuthentication',
    ],

    # 'DEFAULT_SCHEMA_CLASS': ['rest_framework.schemas.coreapi.AutoSchema',]
}


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# STATIC_URL = "/static/"
# # Note: Replace 'supersecure.codes' with your domain
# STATIC_ROOT = "/home/admin1/Documents/Solar_Admin/Is-It-Worth-Getting-a-10kW-Solar-System-/admin_crm/static"
# STATICFILES_DIRS = [BASE_DIR / "static"]

# STATIC_URL = "/static/"
# # Note: Replace 'supersecure.codes' with your domain
# STATIC_ROOT = "/var/www/solar365.co.in/static"
# STATICFILES_DIRS = [BASE_DIR / "static"]

# STATIC_URL = "static/"

# STATICFILES_DIRS = [
#     BASE_DIR / "static",  
# ]

# STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

AUTH_KEY = 'db0e05bd-04a6-11ec-a13b-0200cd936042'
SENDER_ID = 'SLRPNL'
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = "smtp.gmail.com"
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'pratikshabhardwaj60@gmail.com'
# EMAIL_HOST_PASSWORD = "aqjpqslslndkmlhf"

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = '3dmodel.axesgeeks@gmail.com'
EMAIL_HOST_PASSWORD = "tprmeozybgzgdheb"

# CELERY_BROKER_URL = "redis://redis:6379"
# CELERY_RESULT_BACKEND = "redis://redis:6379"
# CELERY_BROKER_URL = "redis://65.1.123.138:6379"
# CELERY_RESULT_BACKEND = "redis://65.1.123.138:6379"
CELERY_BROKER_URL = "redis://localhost:6379"
CELERY_RESULT_BACKEND = "redis://localhost:6379"

# CELERY_BROKER_URL = "redis://127.0.0.1:6379"
# CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379"

CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Kolkata'


# SECURE_SSL_REDIRECT=True
# SESSION_COOKIE_SECURE=True
# CSRF_COOKIE_SECURE=True